name: Build Docker image

on:
  push:
    branches: [ main ]
#     tags: []        
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - 
        uses: actions/checkout@v2
      - 
        name: echo
        run: echo $GITHUB_REPOSITORY-test:$GITHUB_REF
#       -
#         name: Set up Docker Buildx
#         uses: docker/setup-buildx-action@v1
#       -
#         name: Login to DockerHub
#         uses: docker/login-action@v1 
#         with:
#           username: ${{ secrets.DOCKERHUB_USERNAME }}
#           password: ${{ secrets.DOCKERHUB_TOKEN }}
#       -
#         name: Build and push
#         id: docker_build
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: $GITHUB_REPOSITORY:$GITHUB_REF
# #           tags: whitespots/dojo-empty-engagements-closer:$GITHUB_REF
#       -
#         name: Image digest
#         run: echo ${{ steps.docker_build.outputs.digest }}
